# The configuration file for docking actions that robots can perform
# FleetName: The name of the fleet
#   DockName: The name of the docking waypoint
#     level_name: The level name
#     path: The waypoints that the robot will pass through during the docking process)
#     finish_waypoint: The name of the waypoint where the robot will end up at the end of the docking process
#
# Note: These waypoints are in (x meters, y meters, yaw radian) form
#
# If loaded correctly, you will be able to echo the msg via:
#   ros2 topic echo /dock_summary --qos-durability transient_local --qos-reliability reliable
#
# Configuring Cleaning path:
#    The full cleaning path which the robot will travel along. When configuring, the first
#    waypoint is required to be the current robot's waypoint.


cleanerBotA:
  clean_sala3:
    level_name: "L1"
    path: [ [34.3, -8.38, 0.0],
            [34.3, -3.58, 0.0],
            [39.0, -1.85, 0.0],
            [39.54, -3.92, 0.0]]
    finish_waypoint: "clean_sala3"
  clean_sala2:
    level_name: "L1"
    path: [ [2.73, -2.4, 0.0],
            [7.32, -2.44, 0.0],
            [6.27, -4.76, 0.0]
            ]
    finish_waypoint: "clean_sala2"
